### PR TITLE
 Added some comments

### PR DESCRIPTION
**Pull request by AdamT20054**
Just added some comments to the templates. Nothing needs updating (nothing in the readme or anything like that)

### CODE REVIEW

**Comment by AdamT20054** [comment]
You should just be able to merge with no conflicts

**Comment by TFAGaming** [comment]
I'm still a beginner on GitHub and idk a lot of features... ;-;

**Comment by AdamT20054** [comment]
> I'm still a beginner on GitHub and idk a lot of features... ;-;
> 
> Edit: AHH I understand, thanks :)

Just for future reference (might help a bit)

People can fork your repo, add changes and then make a pull request (like this) to "merge" the changes to your current version. github does a good job of making sure you have no issues merging it (like if they're trying to merge an old version). You can see the code changes to see what they've added and deleted and if you want to test it you can test it, or you can set up automatic tests that run when the pull request is made (there's some pre-setup ones on the Actions/marketplace bit).

If you ever need anything explaining just lmk and I'll try my best :)

**Comment by TFAGaming** [comment]
Ah good, understood. Thanks :]

**Pull request merged**
